#Fri Jan 20 12:12:28 EAT 2017

#********************** GePG Response codes and Status ************************************

7101 = Successful
7201 = Failure
7202 = Required header is not given
7203= Unauthorized
7204= Bill does not exist
7205= Invalid service provider
7206= Service provider is not active
7207= Duplicate payment
7208= Invalid business account
7209= Business account is not active
7210= Collection account balance limit reached
7211= Payment service provider code did not match Bill service provider code
7212= Payment currency did not match Bill currency
7213= Bill has expired
7214= Insufficient amount paid
7215= Invalid payment service provider
7216= Payment service provider is not active
7217= No payer email or phone number
7218= Wrong payer identity
7219= Wrong currency
7220= Sub Service provider is inactive
7221= Wrong bill equivalent amount
7222= Wrong bill miscellaneous amount
7223= Invalid or inactive gfs or service type
7224= Wrong bill amount
7225= Blank bill reference number or code
7226= Duplicate bill information
7227= Blank bill identification number
7228= Invalid sub service provider
7229= Wrong bill item gfs or payment type code
7230= Wrong bill generation date
7231= Wrong bill expiry date
7232= Consumer already started by another process
7233= Consumer already stopped by another process
7234= Wrong bill payment option
7235= Bill creation completed successfully
7236= Bill creation completed with errors
7237= Bill detail creation completed successfully
7238= Bill detail creation completed with errors
7239= No external bill system settings found
7240= Failed to save transaction
7241= Invalid session
7242= Invalid request data
7243= Invalid credit account
7244= Invalid credit amount
7245= Invalid creditor bic
7246= Invalid debit account
7247= Invalid debit amount
7248= Invalid debitor bic
7249= Wrong transfer date
7250= Wrong transfer amounts
7251= Wrong transfer transaction
7252= Settlement transaction created successfully
7253= Settlement transaction created with errors 
7254= Invalid use payment reference, use "Y" or "N"
7255= Invalid item billed amount
7256= Invalid item equivalent amount
7257= Invalid item miscellaneous amount
7258= Total item billed amount mismatches the bill amount
7259= Total item equivalent amount mismatches the bill equivalent amount
7260= Total item miscellaneous amount mismatches the bill miscellaneous amount
7261= Defect bill saved successfully
7262= Defect bill saved with errors
7263= Defect bill items saved successfully
7264= Defect bill items saved with errors
7265= Bill items saved successfully
7266= Bill items saved with errors
7267= Invalid email address
7268= Invalid phone number
7269= Invalid Service Provider System Id
7270= Settlement transaction update completed successfully
7271= Settlement transaction update completed with errors
7272= Defect Settlement transaction saved successfully
7273= Defect Settlement transaction saved with errors
7274= Duplicate Settlement transaction
7275= Invalid Service Provider Payer Id
7276= Invalid Service Provider Payer Name
7277= Invalid bill description
7278= Invalid bill approval user
7279= Bill already settled
7280= Bill expired and bill move process failed
7281= Invalid payment transaction date
7282= Invalid payer email or phone number
7283= Bill has been cancelled
7284= Payment currency did not match collection account currency
7285= Invalid bill generation user
7286= Bill cancellation process failed
7287= Bill control or reference number is invalid. It has to be a number.
7288= Disbursement request did not match signature
7289= Invalid disbursement batch generated date
7290= Total disbursement batch amount cannot be zero(0)
7291= Total disbursement batch amount is not equal to summation of disbursement items
7292= Duplicate disbursement batch
7293= Invalid disbursement pay option
7294= Invalid disbursement batch scheduled date
7295= Invalid disbursement notification template
7296= Disbursement notification template is not active
7297= Inactive currency
7298= Invalid currency for disbursement
7299= Batch item(recipients) recipients should not exceed 
7301= Bill has been paid partially
7302= Paid amount is not exact billed amount
7303= Invalid Signature
7304= Invalid Signature Configuration  
7305= Invalid batch start and end date 
7306= Batch has no item(transaction)
7307= Inconsistency batch start, end and generated date 
7308= Invalid value in transfer reserved field two
7309= Invalid value in transfer reserved field three  
7310= Invalid transfer credit or debit account 
7311= Configurations file for signature does not exist in specified path
7312= Batch does not exist
7313= Cancel is only for auto pay batch
7314= Batch already on disbursement process, cancellation process failed
7315= Batch cancellation process failed
7316= Batch already canceled
7317= Error on processing request
7318= Invalid reconciliation request date
7319= Reconciliation request date is out of allowable range
7320= Invalid reconciliation request options
7321= Request can not completed at this time, try later

#Green reserved codes
7401 = Problem occurred. Please try again later
7402 = Invalid value format. Cents value is made up exclusively of one or more digits.
7403 = You request is being processed, Please wait!.
7404 = No token found!.
7405 = Unknown meter number!.
7406 = Meter is blocked!.
7407 = Insufficient funds in your retail account!.
7408 = There are pending Key Change Tokens that need to be printed.
7409 = The debt amount due is more than or equal to the purchase amount. This is not allowed. Please tender more money.
